### ISSUE TITLE
Is there a plan to upgrade the master branch to .net 6 or 7?

### ISSUE THREAD

**Issue by EanCuznaivy** [stratisproject/StratisFullNode#1091]
Cause I found it hard to build this project on my Apple M1 MacBook :)
I noticed a `feature/dotnet6` branch with some commits behind the master branch, actually, I'm using this branch in my local env. Just wondering if is there a plan to upgrade the master to .net 6 or 7.
Thx for your answers.

**Comment by StratisIain** [comment]
Hi @EanCuznaivy 

The `feature/dotnet6` will become the latest relaese very shortly.

**Comment by EanCuznaivy** [comment]
> Hi @EanCuznaivy
> 
> The `feature/dotnet6` will become the latest relaese very shortly.

Copy, thx

**Comment by ELHARAKA** [comment]
> Hi @EanCuznaivy
> 
> The `feature/dotnet6` will become the latest relaese very shortly.

iis very shortly means one two years?
