### ISSUE TITLE
imho bad things about strax / stratis

### ISSUE THREAD

**Issue by weetie** [stratisproject/StratisFullNode#325]
**written in C#**
- you see this maybe as advantage, but as pure linux server user, I just hate it.
- you can run it with docker, but it is not really stable, has memory problems (better since the switch to strax, but when blockchain grows this will be again a problem) and staking is somehow ending for no reasons, happening every few weeks.
- hundreds of warnings during compile - honestly is this the way of building trustworthy software ?
- I bet nerds do not trust or like this language, so I would consider to switch to golang, rust or whatever is working natively on linux.

**not having a fixed main address**
- this is by far the most annoying thing if you reinstall your wallet, it just uses new addresses (without possibility to use the old one) and your coins are soon spread around. The only and best way I found was moving all coins to a new address with could bring you in a lot of problems explaining this to tax office.
- backup of the wallet file is by far the better method and works at least.

**Comment by dev0tion** [comment]
Sincerly hope you are trolling.

**Comment by weetie** [comment]
$0.44 during a bull run is trolling...

or maybe the great plan of inflation
like from https://chainz.cryptoid.info/strax/address.dws?XCb7PegDAmE1kXeFeQVXbt411cTjHLaExV.htm

or the extremly stable wallets *irony* which can be run unattended for maybe 4 weeks

**Comment by fassadlr** [comment]
Hi @weetie , you are more than welcome to raise these issues with me in Discord (fassadlr). Message me there then we can discuss further.

**Comment by fassadlr** [comment]
Link:

https://discord.com/channels/404643249798512652/404646522425442307
