### ISSUE TITLE
developer forum or community?

### ISSUE THREAD

**Issue by sergeystoyan** [stratisproject/StratisFullNode#439]
Hi,

I've started develop basing on stratis and could not find any forum where to ask beginner's questions. The existing documentation is general and outdated. The link in the readme https://discord.gg/9tDyfZs seems not to work. Could you please provide a place to ask/discuss questions? Thank you.

**Comment by StratisIain** [comment]
Hi @sergeystoyan !

The discord link should still work, do you have the Discord app installed? Feel free to present your questions here if you're having difficulty joining Discord though :)

**Comment by sergeystoyan** [comment]
As for the link, it appeared to be a problem of discord cookies. It displayed message: the link is outdated. But once I cleared cookies it worked.

Anyway, probably my question might be useful for many so it is good to post is here.
I want to deploy a new coin network basing on strax in StratisFullNode. It brought me to the following questions:
- which parameters must be changed to isolate the nodes of my network from the strax nodes so that they could not connect to them?  
- how my network nodes can recognize each other?
- as in strax the reward of the genesis block is 0, how the first coins can be mined in a new network?

Thank you!

**Comment by fassadlr** [comment]
Hi @sergeystoyan, please message me in Discord (fassadlr) if you still have questions.
