### ISSUE TITLE
i submitted my csv file 2 weeks ago but no strax yet?

### ISSUE THREAD

**Issue by ehmirpro** [stratisproject/StratisFullNode#449]
Hello 
i submitted my csv file according link below:
https://www.stratisplatform.com/wp-content/uploads/2021/02/STRAX-Token-Swap-Manual-Token-Swap-Windows-v2.pdf

but i haven't received strax yet .
where is problem?

**Comment by fassadlr** [comment]
Hi @ehmirpro please contact us in our official support channel on Discord:

https://discord.com/channels/404643249798512652/404646522425442307
