### ISSUE TITLE
Transaction metadata endpoint

### ISSUE THREAD

**Issue by drmathias** [stratisproject/StratisFullNode#714]
As an API user, I would like to be able to retrieve metadata for a transaction in the mempool. This would allow a dApp to verify that a transaction id supplied by a 3rd party (such as a wallet), relates to a specific transaction that it built and expects to be present in the mempool.

**Comment by zeptin** [comment]
Doesn't `/api/Node/getrawtransaction` do this already? It searches the mempool too.

**Comment by drmathias** [comment]
> Doesn't `/api/Node/getrawtransaction` do this already? It searches the mempool too.

This does seem to fit our needs, thanks :)
