### ISSUE TITLE
Outdated and missing NuGet packages

### ISSUE THREAD

**Issue by drmathias** [stratisproject/StratisFullNode#748]
We are unable to create a Cirrus node that can work with smart contracts, by building it using the packages available on NuGet.org. The node will run, however any smart contract call will result in an exception occurring from a failed call to Stratis.SmartContracts.CLR, for example:

> System.MissingMethodException: Method not found: 'Void Stratis.SmartContracts.CLR.ContractTxData..ctor(Int32, UInt64, Stratis.SmartContracts.RuntimeObserver.Gas, NBitcoin.uint160, System.String, System.Object[], System.String[])'.

The following packages are used:

```xml
<ItemGroup>
  <PackageReference Include="Stratis.Features.Api" Version="1.0.9.4" />
  <PackageReference Include="Stratis.Features.Collateral" Version="4.0.1" />
  <PackageReference Include="Stratis.Features.Notifications" Version="1.0.9.4" />
  <PackageReference Include="Stratis.Features.SmartContracts" Version="1.0.9.4" />
  <PackageReference Include="Stratis.Features.SQLiteWalletRepository" Version="1.0.9.4" />
  <PackageReference Include="Stratis.Features.Wallet" Version="1.0.9.4" />
  <PackageReference Include="Stratis.Sidechains.Networks" Version="1.0.9.4" />
  <PackageReference Include="Stratis.SmartContracts.CLR" Version="2.0.1" />
  <PackageReference Include="Stratis.SmartContracts.Core" Version="2.0.3" />
  <PackageReference Include="Stratis.SmartContracts.Networks" Version="2.0.1" />
</ItemGroup>
```

Building a new version of `Stratis.SmartContracts.CLR` package from the 1.0.9.4 release branch seems to resolve the issue, so it looks as though the current version is simply outdated.

There are a couple of features which are unavailable on NuGet.org as well, including:

* Stratis.Features.SignalR
* Stratis.Features.Diagnostic

Being able to build and run a node by importing packages from NuGet is far simpler for us than maintaining a fork of the project. It will allow us to configure logging targets so we can get structured logging end-to-end, as well as build some neat extensions.

**Comment by mrtpain** [comment]
Also FWIW, Opdex relies on `release/opdex-1.1.0.0` currently, so when that is merged into an official release, it would be greate if this issue could be looked at around that time. 

Anything before will help us stand up the infrastructure but can't be used in practice just yet without the merge and package updates.

**Comment by fassadlr** [comment]
@mrtpain as stated in the Slack channel, we have now pushed the latest Nugts for release/1.1.1.0 and this is merged to your opdex branch. Can we close this issue?

**Comment by drmathias** [comment]
Those updates should be all we need for now, thanks!
