### ISSUE TITLE
DevMode - Get Raw Transaction is null

### ISSUE THREAD

**Issue by mrtpain** [stratisproject/StratisFullNode#827]
When running with `-devmode=miner` the `/getrawtransaction` endpoint returns `null` for valid transaction hashes. 

Testnet works as expected, retrieving and returning the raw transaction details.

**Comment by zeptin** [comment]
Are the transactions in question in the mempool or mined into blocks? If they are in blocks, they will most likely need `-txindex` enabled in order to be retrieved

**Comment by mrtpain** [comment]
> Are the transactions in question in the mempool or mined into blocks? If they are in blocks, they will most likely need `-txindex` enabled in order to be retrieved

Ah that's probably it, we aren't running with `-txindex` in our dev environment. Will give that a shot and close if all works 👍 thanks

**Comment by mrtpain** [comment]
Yes that was it 👍 thanks @zeptin
